### PR TITLE
Feature/Web

### PR DESCRIPTION
**Pull request by Ahmadre**
This PR contains full implementation of latest WebGL Builds into flutter_unity.

I just had to add some tweaks to the existing FlutterUnityPlugin in C# and it worked like a charm with the existing interface.

The example was added and it's working.

Furthermore Android project in example had to use flutter embedding v2. This was also fixed.

### CODE REVIEW

**Comment by Ahmadre** [comment]
A Platform-Interface implementation would be the best here to be able to add seemlessly other platforms in the future. It also helps to avoid platform errors here.

**Comment by Ahmadre** [comment]
Tests are finished! It's working and without any downsides to mobile :) Sending and receiving works and a full example is provided in the example folder (also see the unity folder in web)

**Comment by Ahmadre** [comment]
@GlarGit @marcotuna @cookiejarlid @joaopedro735 

Gentle reminder to review this :)

For all other who want to work with it, add this to your pubspec.yaml:

```yaml
flutter_unity:
  git: 
    url: https://github.com/Ahmadre/flutter-unity.git
    ref: feature/web
```

**Comment by Dapp3rDanH** [comment]
Hello.  Thanks for working on this.  If I wanted to preview this, would I comment out in pubspec.yaml the flutter_unity_widget section and replace with:

flutter_unity:
  git: 
    url: https://github.com/Ahmadre/flutter-unity.git
    ref: feature/web

Or, do I keep flutter_unity_widget: section and add the flutter_unity: section?

Thanks,
Dan

**Comment by Ahmadre** [comment]
> Hello. Thanks for working on this. If I wanted to preview this, would I comment out in pubspec.yaml the flutter_unity_widget section and replace with:
> 
> flutter_unity: git: url: https://github.com/Ahmadre/flutter-unity.git ref: feature/web
> 
> Or, do I keep flutter_unity_widget: section and add the flutter_unity: section?
> 
> Thanks, Dan

I don't know if this is working for flutter_unity_widget (that's a different package!), but I've released my own plugin now: https://pub.dev/packages/unity_widget

Use that and forget flutter_unity_widget. It's very buggy. My Plugin is based and licensed on this plugin and the web version from Samuel I.

**Comment by riccardocescon** [comment]
Hi @Ahmadre i am having this issue #60 on Flutter Web.
I tried your web example but without any success

**Pull request closed without merging**
